version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '3000:3000'  # Maps port 3000 on the host to port 80 in the container
    networks:
      - taskmanager-network
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '5000:5000'  # Maps port 5000 on the host to port 5000 in the container
    networks:
      - taskmanager-network
    depends_on:
      - mysql
    environment:
      - NODE_ENV=development
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=task_manage

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: task_manage
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - '3306:3306'
    networks:
      - taskmanager-network
  
  

volumes:
  mysql-data:

networks:
  taskmanager-network: